package org.example;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.apache.pulsar.client.api.AuthenticationFactory;
import org.apache.pulsar.client.api.Producer;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.PulsarClientException;
import org.apache.pulsar.client.api.Schema;
import org.example.model.ExampleMessage;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;

@SpringBootApplication
@EnableWebMvc
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    @Value("${org.example.topic1}")
    public String topic1;
    @Bean
    @Qualifier("producer")
    public Producer<ExampleMessage> getProducer() throws PulsarClientException {
        try(PulsarClient client = PulsarClient.builder()
                .serviceUrl("pulsar+ssl://pulsar-dev.pulsar-nprod-gcp.collibra-ops.com:6651")
                .authentication(
                        AuthenticationFactory.token("auth-token"))
                .build()) {
            return client.newProducer(Schema.JSON(ExampleMessage.class))
                    .topic(topic1)
                    .create();
        }
    }
}
