server:
  port: 7070

org:
  example:
    topic: "persistent://playground/test/test.topic11.v1"
    pulsar:
      client:
        service-url: "pulsar+ssl://pulsar-dev.pulsar-nprod-gcp.collibra-ops.com:6651"
        authentication:
          plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationToken
          param:
            token: "MzVlN2NjMDYtMGIwMi00Zjk5LWVhNjItZTYwZjU2ZmRmN2VjOmRmNDJmMDhkLTNmNTgtMDZkYy03MmU0LTg0ZTNiOWE3Y2ExYg=="

logging.level.org.apache.pulsar.client: ERROR
logging.level.org.springframework: ERROR