spring:
  pulsar:
    client:
      service-url: "pulsar://localhost:6650"
      authentication:
        plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationToken
        param:
          token: "token"

org:
  example:
    topic-no-schema: "test-topic-no-schema"
    topic-schema: "test-topic-schema"
server:
  port: 7070