package org.example;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;

@SpringBootApplication
@EnableWebMvc
public class SpringbootApp {

    public static void main(String[] args) {
        SpringApplication.run(SpringbootApp.class, args);
    }
}
